version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: ./web-app/Dockerfile
    container_name: flask_app
    volumes:
      - ./web-app/app:/app
      - shared_data:/app/databases
    ports:
      - "5000:5000"
    networks:
      - app-network
  
  nginx:
    image: nginx:1.27.3
    container_name: nginx_server
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./web-app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web-app/nginx/certs:/etc/nginx/certs
    networks:
      - app-network
    depends_on:
      - flask

  console-app:
      build:
        context: .
        dockerfile: ./console-app/Dockerfile
      container_name: console-app
      volumes:
        - ./console-app:/app
        - shared_data:/app/databases
      networks:
        - app-network

volumes:
  shared_data:
    driver: local

networks:
  app-network:
    driver: bridge