version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
  
  nginx:
    image: nginx:1.27.3
    container_name: nginx_server
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - flask