name: Generate Javadoc and Deploy to GitHub Pages

permissions:
    contents: write

on: [pull_request]

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven and generate Javadoc
        run: |
          cd console-app
          mvn clean install
          mvn javadoc:javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs
