name: Generate Javadoc and Deploy to GitHub Pages

permissions:
    contents: write

on: [pull_request]

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le depot
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 3 : Créer la documentation Javadoc
      - name: Build with Maven and generate Javadoc
        run: |
          cd console-app
          mvn clean install
          mvn javadoc:javadoc
      
      # Afficher le contenu du dossier javadoc
      - name: Verify Javadoc Directory
        run: ls -alh ./console-app/target/site/apidocs

      # Étape 4 : Uploader la documentation Javadoc
      - name: Upload Javadoc
        run: |
          cd console-app
          git checkout gh-pages
          git rm -rf .
          cp -r ./console-app/target/site/apidocs/* .
          git add .
          git commit -m "Update Javadoc"
          git push origin gh-pages

      # Étape 5 : Deployer la documentation Javadoc    
      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .console-app/target/site/apidocs
