name: Java CI with Maven

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 3 : Restaurer le cache Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Étape 4 : Exécuter les test Maven
      - name: Set up and run tests
        run: |
          cd console-app
          mvn clean package install
          mvn test

      # Étape 5 : Générer le rapport Jacoco
      - name: Generate JaCoCo report
        run: |
          cd console-app
          mvn dependency:purge-local-repository clean install
          mvn clean test jacoco:report
      
      # Étape 6 : Upload sur CodeCov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}